name: "Chromatic"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
  chromatic:
    runs-on: ubuntu-latest
    needs: cache-and-install
    steps:
      - name: pwd
        run: pwd

      - name: log file list
        run: ls -la

      - name: Run Chromatic for editor-ui
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/ui
          zip: true